---
driver:
  name: docker
  binary: docker.io

provisioner:
  name: chef_zero

platforms:
   - name: centos-7.1
    driver_config:
       image: centos:7.1
       platform: centos
suites:
  - name: default
    run_list:

      - recipe[apachenew::default]

    attributes:
